// autogenerated by typings-for-css-modules-loader.
declare namespace GlobalModuleScssNamespace {
  export interface IGlobalModuleScss {
    "--photo-breakpoint": string;
  }
}

declare const GlobalModuleScssModule: GlobalModuleScssNamespace.IGlobalModuleScss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: GlobalModuleScssNamespace.IGlobalModuleScss;
};

export = GlobalModuleScssModule;
