// autogenerated by typings-for-css-modules-loader.
declare namespace PhotoModuleScssNamespace {
  export interface IPhotoModuleScss {
    caption: string;
    photo: string;
    "photo-div": string;
    photoDiv: string;
    roundedPhoto: string;
  }
}

declare const PhotoModuleScssModule: PhotoModuleScssNamespace.IPhotoModuleScss & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: PhotoModuleScssNamespace.IPhotoModuleScss;
};

export = PhotoModuleScssModule;
